### ISSUE TITLE
Replacing measurement names should not be default

### ISSUE THREAD

**Issue by szibis** [escalate/influxdb-csv-importer#3]
It is allowed to have a measurement with dots in name https://github.com/influxdata/influxdb/pull/4112.
There is no info in the doc about measurement names or I miss something - https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/#measurement

Can we make this configurable or remove this line?
https://github.com/escalate/influxdb-csv-importer/blob/master/csvimporter.py#L87

**Comment by escalate** [comment]
This was just a way at the beginning to get similar measurement names.
I agree with you, it is not necessary as long as you use a InfluxDB version > 0.9.1.
Please take a look at issue influxdata/influxdb#3457 to see the problems with dots.
I will create a patch to make the replacing optional.
