### ISSUE TITLE
Don't input data

### ISSUE THREAD

**Issue by estevamdf2** [escalate/influxdb-csv-importer#5]
Hi friends,

After run this application with this params

`./csvimporter.py --server=localhost --port=8083 --database=telemetria --timestamp-format=datetime --verbose teste.csv 
`

I had this output log

`
DEBUG: CSV filename is set to "teste.csv"
DEBUG: CSV delimter is set to ","

DEBUG: InfluxDB sever address is set to "localhost"
DEBUG: InfluxDB sever port is set to "8083"
DEBUG: InfluxDB database is set to "telemetria"
DEBUG: Timestamp format is set to "datetime"
DEBUG: Timestamp timezone is set to "UTC"
DEBUG: Toggle for int to float conversion is set to "True"
`

But when i go to view data in database is empty.

I used one csv file with this data for test

`
#datatype measurement,tag,dateTime:RFC3339
m,host,time

mem,host1,2020-01-01T00:00:00Z
mem,host2,2020-01-01T00:00:00Z
`

What will i do to solve this problem?

**Comment by escalate** [comment]
Hello @estevamdf2
Which InfluxDB version are you using? 
Maybe it would help if you define the column that contains the timestamp.
You can do this with the option --timestamp-column.
Many greetings
Felix

**Comment by escalate** [comment]
I am closing the issue as there are no further questions.
